### ISSUE TITLE
Match e-mail address

### ISSUE THREAD

**Issue by cyucelen** [cyucelen/marker#10]
Create a matcher that matches e-mail addresses such as:

```
foo@bar.com
john@doe.io
etc..
```

**Comment by richardbertozzo** [comment]
Hi @cyucelen 

Can i get this one?

**Comment by nikolaev-dm** [comment]
Hi @cyucelen @richardbertozzo 
I created a PR #15 to solve this issue. I want to get some feedback, like code review.
Thank you!

**Comment by cyucelen** [comment]
Hi @johnny-silverhand @richardbertozzo 
I just wrote a review. We can discuss which RFC standard to match and which regular expression we are going to use for this feature. You guys may look over some email RFC standards.

**Comment by richardbertozzo** [comment]
Yes, @johnny-silverhand maybe can use this for the regex: https://gist.github.com/gregseth/5582254. Has simpler version.

**Comment by nikolaev-dm** [comment]
@richardbertozzo Looks good to me! Because the official standard is considered RFC 2822. At the same time the email format is formally defined in RFC 5322. So, Which of the RFCs will we choose?

**Comment by richardbertozzo** [comment]
I think the Simpler version in the link its great and will reach 99% of emails.

**Comment by cyucelen** [comment]
Lets go with the RFC5322, since it obsoletes RFC2822.

**Comment by cyucelen** [comment]
@johnny-silverhand @richardbertozzo how is it going guys? Need any help?

**Comment by richardbertozzo** [comment]
I can send a version, but will override the PR of @johnny-silverhand.

**Comment by cyucelen** [comment]
Since implementation is small, make it.
