### ISSUE TITLE
Documentation for MatchSurrounded

### ISSUE THREAD

**Issue by cyucelen** [cyucelen/marker#12]
Write a simple usage documentation and example for [MatchSurrounded](https://github.com/cyucelen/marker/blob/8e2834d5c6b6c94d0566407d9bee9b7b9bc56d57/matcher.go#L50) in [README](https://github.com/cyucelen/marker/blob/master/README.md).

**Comment by yogesh-desai** [comment]
Hi @cyucelen,
I have created a PR:https://github.com/cyucelen/marker/pull/16 for the above issue. Please review and give feedback.
Thank you.

**Comment by cyucelen** [comment]
Hey @yogesh-desai 
I am thinking about, _somehow_ find a standard way to create colorful terminal output pictures for our README file. Because it is hard to keep the pictures tidy and in order with respect to size, font family, font color, background color, etc. Some online IDE outputs, online terminal emulators _(if there are any)_ , or maybe we can create some SVGs.

Created the #18 to discuss this.

**Comment by yogesh-desai** [comment]
@cyucelen Agree in keeping the ReadMe tidy. I don't have any suggestion/solution for that until now, need to do some research for it. Do let me know if you know any solution already, to solve the issue.
Thank you.

**Comment by jnatalzia** [comment]
PR was merged, good to close this?
