### ISSUE TITLE
Variadic Mark function

### ISSUE THREAD

**Issue by cyucelen** [cyucelen/marker#13]
Create a variadic **Mark** function that can take an arbitrary number of **Matchers** and colorizes the matches.

**Comment by dapryor** [comment]
Are you wanting to replace the old Mark function with this new version?
Edit:
Are you wanting to expect a slice of strings in return?

**Comment by cyucelen** [comment]
Sorry for the lack of information about the task. 

I am expecting a new variadic **Mark** function to take a string, a color and an arbitrary number of **Matchers** and return a colorized string that all Matchers applied to it.

**Comment by dapryor** [comment]
No worries.

I think what I submitted may not be exactly what you want, so I will come back to that after work.

**Comment by cyucelen** [comment]
Waiting for your commits. Thanks!

**Comment by dapryor** [comment]
@cyucelen If you have free time, would you review pull request #14 and let me know what changes you would want to see.  I missed that you have a builder.go file, so I didn't add the new function to that file.

**Comment by dapryor** [comment]
I made this a separate function to avoid breaking any code.  We can go in and restructure Mark into being MarkMany then make the original Mark a private function.

Currently it is setup like:
marker.go
``` go
func MarkMany(str string, c *color.Color, matcherFuncs ...MatcherFunc) string
```

How to use:
``` go
str := MarkMany("Skydome is Skydome. Give yourself freedom.", myColor, MatchAll("Skydome"), MatchAll("yourself"))
```
![image](https://user-images.githubusercontent.com/9582780/66359547-94cd2b80-e945-11e9-9002-a1eca8a7ddde.png)

builder.go
``` go
func (m *MarkBuilder) MarkMany(c *color.Color, matcherFuncs ...MatcherFunc) *MarkBuilder
```

How to use:
``` go
b := MarkBuilder{}
actualString := b.SetString("Skydome is a data company.").
		MarkMany(redFg, MatchAll("data"), MatchAll("company")).
		Build()
```
![image](https://user-images.githubusercontent.com/9582780/66359489-59326180-e945-11e9-93db-cf2a8c5ac555.png)
