### ISSUE TITLE
Keeping in touch

### ISSUE THREAD

**Issue by cyucelen** [cyucelen/marker#29]
Since past two weeks, I feel like we built an awesome synergy among us. I really enjoyed working with you guys, I believe you all valuable and we can learn a lot from each other! 

So, i want to discuss about using a platform -like Slack but without limitations- for keeping in touch. By this way, i think, we can develop marker better and faster! I believe communication channel matters for efficiency.

Even we can build new fantastic projects as a team and welcome new comers to our culture we just started to built!

Lets discuss if it is a good idea and which platform should we use.

**Comment by dapryor** [comment]
I am a fan of discord 👍🏻

**Comment by jnatalzia** [comment]
Discord or slack are both great!

Agree that we've seen some great progress and teamwork here 💪

**Comment by cyucelen** [comment]
So lets do some brainstorming about the name of the team. Then we can create a discord server! 

Waiting for your suggestions.
https://poll.ly/#/PEpMvyQg

**Comment by cyucelen** [comment]
Although i like the names, maybe we should be more language, or repository independent :smile: 

Planning to do new stuff using geek techs with you guys! Don't be specific to the project or technology, unleash your imagination! 

Lets put a deadline to the,
**5:00:00 PM** _(UTC)_
_Tuesday, October 29, 2019_

If we can't find a name we like, lets go with a temporary one, because I want to keep in touch!

cc @jnatalzia @dapryor @Darkclainer

**Comment by Darkclainer** [comment]
upvote for discord

**Comment by cyucelen** [comment]
So, here is our link!

https://discord.gg/kaUtncA

@jnatalzia @Darkclainer @dapryor
