### ISSUE TITLE
Match surrounded characters

### ISSUE THREAD

**Issue by jnatalzia** [cyucelen/marker#4]
Oftentimes in log files, the beginning of the log has certain characters encasing it ex: `[INFO]`. Create a matcher which takes in surrounding characters and colorizes the encased letters, inclusive of the surrounding characters.

**Comment by jnatalzia** [comment]
Could I get this assigned to myself please? And the hacktoberfest label?

**Comment by cyucelen** [comment]
It looks pretty useful. Looking forward for your contribution!

**Comment by jnatalzia** [comment]
Thanks! :)
